apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: react-app
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: react-app
  template:
    metadata:
      labels:
        run: react-app
    spec:
      containers:
      - image: gcr.io/rugged-shell-260219/react-app:latest
        name: react-app
        ports:
        - containerPort: 786
